name: eiviznho
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.20.1
  june: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
